version: '3'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432" # デバッグ用
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./application:/code/
      - ./static:/static
    ports:
      - "8000:8000"
      - "8080:8080" # デバッグ用
    depends_on:
      db:
        condition: service_healthy
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file:
      - .env

volumes:
  db_data:


networks:
  default:
    name: testnet
