version: '3'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432" # デバッグ用
    networks:
      - practice_appform_app_db
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    command: sh -c "/usr/local/bin/entrypoint.sh"
    env_file:
      - .env
    volumes:
      - ./application:/code/
      - ./static:/static
    ports:
      - "8000:8000"
      - "8080:8080" # デバッグ用
    depends_on:
      db:
        condition: service_healthy
    networks:
      - practice_appform_app_db
      - practice_appform_app_web
  # AWSをローカルで検証するためのMockサーバー
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    env_file:
      - .env
    volumes:
      - localstack_data:/tmp/localstack/data
      - localstack_bin:/var/lib/localstack
    networks:
      - practice_appform_app_web
  nginx:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - practice_appform_app_web
volumes:
  db_data:
  localstack_data:
  localstack_bin:
networks:
  practice_appform_app_db:
  practice_appform_app_web:
