version: '3'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    command: sh -c "chmod 755 /code/entrypoint.sh && /code/entrypoint.sh"
    env_file:
      - .env.prod
    volumes:
      - ./application:/code/
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  web:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    env_file:
      - .env.prod
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
